global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ingest-service'
    static_configs:
      - targets: ['ingest-service:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'api-service'
    static_configs:
      - targets: ['api-service:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'ml-service'
    static_configs:
      - targets: ['ml-service:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
    scrape_interval: 60s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 60s